; Media Downloader - unified "pick your version" bootstrapper installer.
;
; ONE published artifact with a stable name (MediaDownloaderSetup.exe) that
; installs ANY released version. It shows a wizard page listing the released
; versions (newest stable pre-selected; a checkbox reveals beta/pre-release
; builds), downloads the chosen version's REAL per-version installer from the
; PUBLIC releases repo, verifies its SHA-256, and runs it silently.
;
; The real per-version installers still live as GitHub Release assets in
;   smithmediaindustriesinc-code/Media-Downloader-Releases   (public, source-free)
; alongside a versions.json manifest generated by tools/gen_manifest.py:
;   [ { "version":"1.7.0", "channel":"stable", "date":"2026-08-29",
;       "asset":"MediaDownloaderSetup1.7.0.exe",
;       "url":"https://github.com/.../releases/download/v1.7.0/MediaDownloaderSetup1.7.0.exe",
;       "sha256":"<64 hex>", "notes":"...",
;       "beta_variant_url":"https://.../MediaDownloaderSetup1.7.0-beta.exe" },  // optional
;     ... ]  // newest-first; "channel":"beta" == a GitHub prerelease
;
; This bootstrapper has its OWN version (BootVersion) and is rebuilt only when
; THIS file changes - not on every app release. Build:
;   ISCC bootstrapper.iss    ->   installer_output\MediaDownloaderSetup.exe
; Requires Inno Setup 6.3+ (CreateDownloadPage with a hash argument).

#define MyAppName "Media Downloader"
#define BootVersion "1.0.0"
#define ManifestURL "https://raw.githubusercontent.com/smithmediaindustriesinc-code/Media-Downloader-Releases/main/versions.json"

[Setup]
AppId={{B6E1B5C4-8B1B-4A3E-9C2A-MEDIADOWNLOADER-BOOT}}
AppName={#MyAppName} Installer
AppVersion={#BootVersion}
VersionInfoVersion={#BootVersion}
VersionInfoCompany=Smith Media Industries inc.
VersionInfoDescription={#MyAppName} Setup
DefaultDirName={localappdata}\Temp\MediaDownloaderBootstrap
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableReadyPage=yes
DisableFinishedPage=yes
Uninstallable=no
CreateAppDir=no
; The bootstrapper itself needs no elevation - it only downloads to {tmp}
; and runs the real per-version installer, which prompts for admin itself
; if its install location (Program Files) needs it.
PrivilegesRequired=lowest
OutputDir=installer_output
OutputBaseFilename=MediaDownloaderSetup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
SetupIconFile=installer_icon.ico
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0.17763

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]
var
  VersionPage: TWizardPage;
  VersionCombo: TNewComboBox;
  BetaCheck: TNewCheckBox;
  NotesLabel: TNewStaticText;
  VerList, ChanList, UrlList, HashList, NotesList: TStringList;

function DownloadText(const Url: string; out Body: string): Boolean;
var
  Req: Variant;
begin
  Result := False;
  try
    Req := CreateOleObject('WinHttp.WinHttpRequest.5.1');
    Req.Open('GET', Url, False);
    Req.SetRequestHeader('User-Agent', 'MediaDownloaderBootstrap');
    Req.Send('');
    if Req.Status = 200 then
    begin
      Body := Req.ResponseText;
      Result := True;
    end;
  except
    Result := False;
  end;
end;

// Minimal parser for the flat array-of-objects manifest above. Inno has no
// JSON library; the manifest shape is fixed because we generate it.
function JsonStr(const Obj, Key: string): string;
var
  P, Q: Integer;
  Needle: string;
begin
  Result := '';
  Needle := '"' + Key + '"';
  P := Pos(Needle, Obj);
  if P = 0 then Exit;
  P := P + Length(Needle);
  while (P <= Length(Obj)) and (Obj[P] <> ':') do Inc(P);
  Inc(P);
  while (P <= Length(Obj)) and (Obj[P] <> '"') do Inc(P);
  Inc(P);
  Q := P;
  while (Q <= Length(Obj)) and (Obj[Q] <> '"') do Inc(Q);
  Result := Copy(Obj, P, Q - P);
end;

procedure ParseManifest(const Body: string);
var
  I, Depth, Start: Integer;
  Obj: string;
begin
  VerList := TStringList.Create;  ChanList := TStringList.Create;
  UrlList := TStringList.Create;  HashList := TStringList.Create;
  NotesList := TStringList.Create;
  Depth := 0; Start := 0;
  for I := 1 to Length(Body) do
  begin
    if Body[I] = '{' then
    begin
      if Depth = 0 then Start := I;
      Inc(Depth);
    end
    else if Body[I] = '}' then
    begin
      Dec(Depth);
      if Depth = 0 then
      begin
        Obj := Copy(Body, Start, I - Start + 1);
        if JsonStr(Obj, 'url') <> '' then
        begin
          VerList.Add(JsonStr(Obj, 'version'));
          ChanList.Add(JsonStr(Obj, 'channel'));
          UrlList.Add(JsonStr(Obj, 'url'));
          HashList.Add(JsonStr(Obj, 'sha256'));
          NotesList.Add(JsonStr(Obj, 'notes'));
        end;
      end;
    end;
  end;
end;

function RowLabel(I: Integer): string;
begin
  Result := VerList[I] + ' (' + ChanList[I] + ')';
end;

procedure RefreshCombo;
var
  I: Integer;
  ShowBeta: Boolean;
begin
  ShowBeta := BetaCheck.Checked;
  VersionCombo.Items.Clear;
  for I := 0 to VerList.Count - 1 do
    if (ChanList[I] = 'stable') or ShowBeta then
      VersionCombo.Items.Add(RowLabel(I));
  if VersionCombo.Items.Count > 0 then
    VersionCombo.ItemIndex := 0;   // manifest is newest-first
end;

function SelectedIndex: Integer;
var
  I: Integer;
begin
  Result := -1;
  if VersionCombo.ItemIndex < 0 then Exit;
  for I := 0 to VerList.Count - 1 do
    if VersionCombo.Items[VersionCombo.ItemIndex] = RowLabel(I) then
    begin
      Result := I;
      Exit;
    end;
end;

procedure UpdateNotes;
var
  I: Integer;
begin
  I := SelectedIndex;
  if I >= 0 then NotesLabel.Caption := NotesList[I] else NotesLabel.Caption := '';
end;

procedure ComboChange(Sender: TObject); begin UpdateNotes; end;
procedure BetaClick(Sender: TObject); begin RefreshCombo; UpdateNotes; end;

procedure InitializeWizard;
var
  Body: string;
begin
  VersionPage := CreateCustomPage(wpWelcome, 'Choose a version',
    'Pick which version of Media Downloader to install. The latest stable release is selected by default.');

  VersionCombo := TNewComboBox.Create(VersionPage);
  VersionCombo.Parent := VersionPage.Surface;
  VersionCombo.Left := 0;
  VersionCombo.Top := ScaleY(8);
  VersionCombo.Width := VersionPage.SurfaceWidth;
  VersionCombo.Style := csDropDownList;
  VersionCombo.OnChange := @ComboChange;

  BetaCheck := TNewCheckBox.Create(VersionPage);
  BetaCheck.Parent := VersionPage.Surface;
  BetaCheck.Left := 0;
  BetaCheck.Top := VersionCombo.Top + VersionCombo.Height + ScaleY(12);
  BetaCheck.Width := VersionPage.SurfaceWidth;
  BetaCheck.Caption := 'Show beta / pre-release builds';
  BetaCheck.Checked := False;
  BetaCheck.OnClick := @BetaClick;

  NotesLabel := TNewStaticText.Create(VersionPage);
  NotesLabel.Parent := VersionPage.Surface;
  NotesLabel.Left := 0;
  NotesLabel.Top := BetaCheck.Top + BetaCheck.Height + ScaleY(16);
  NotesLabel.Width := VersionPage.SurfaceWidth;
  NotesLabel.WordWrap := True;
  NotesLabel.Caption := '';

  if not DownloadText('{#ManifestURL}', Body) then
  begin
    MsgBox('Could not reach the version list. Check your internet connection and try again.',
           mbCriticalError, MB_OK);
    Abort;
  end;
  ParseManifest(Body);
  if VerList.Count = 0 then
  begin
    MsgBox('The version list came back empty or unreadable. Try again later.',
           mbCriticalError, MB_OK);
    Abort;
  end;
  RefreshCombo;
  UpdateNotes;
end;

// After the (empty) install: download the chosen per-version installer,
// verify its SHA-256, and run it silently.
procedure CurStepChanged(CurStep: TSetupStep);
var
  Idx: Integer;
  Url, Hash, TmpExe: string;
  ResultCode: Integer;
  DownloadPage: TDownloadWizardPage;
begin
  if CurStep <> ssPostInstall then Exit;
  Idx := SelectedIndex;
  if Idx < 0 then
  begin
    MsgBox('No version was selected.', mbError, MB_OK);
    Abort;
  end;
  Url := UrlList[Idx];
  Hash := HashList[Idx];
  TmpExe := ExpandConstant('{tmp}\MediaDownloaderSetup_selected.exe');

  DownloadPage := CreateDownloadPage('Downloading Media Downloader ' + VerList[Idx],
    'Fetching the installer for the version you chose...', nil);
  DownloadPage.Clear;
  DownloadPage.Add(Url, 'MediaDownloaderSetup_selected.exe', Hash);  // '' hash = skip check
  DownloadPage.Show;
  try
    try
      DownloadPage.Download;
    except
      MsgBox('The download failed: ' + GetExceptionMessage + #13#10 +
             'The version you picked may have been removed, or your connection dropped.',
             mbCriticalError, MB_OK);
      Abort;
    end;
  finally
    DownloadPage.Hide;
  end;

  if not FileExists(TmpExe) then
  begin
    MsgBox('The downloaded installer is missing.', mbCriticalError, MB_OK);
    Abort;
  end;

  if not Exec(TmpExe, '/SILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_SHOW,
              ewWaitUntilTerminated, ResultCode) then
    MsgBox('Could not start the installer for the selected version.', mbCriticalError, MB_OK)
  else if ResultCode <> 0 then
    MsgBox('The version installer exited with code ' + IntToStr(ResultCode) + '.', mbError, MB_OK);
end;
